name: pomodoro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_bloc: 8.0.1
  intl: 0.17.0
  timezone: 0.8.0
  shared_preferences: 2.0.15
  google_fonts: 2.3.1
  gap: 2.0.0
  equatable: 2.0.3
  audioplayers: 1.0.1
  move_to_background: 1.0.2
  flutter_local_notifications: 9.4.0
  flutter_native_timezone: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/sounds/
  uses-material-design: true

